---
- name: Ensure that yaya user is present
  hosts: all
  become: true

  tasks:
    - name: Create user
      user:
          name: "{{ username['uname']['name'] }}"
          password: test
          comment: "{{ username['uname']['desc'] }}"
          uid: 4004
          state: present

