---
- name: Ensure that yaya user is present
  hosts: all
  become: true

  tasks:
    - name: Load vars from file
      include_vars:
        file: secret.yml

    - name: Display the encrypt VARS
      debug:
        msg: "{{ secret }}"

    - name: Create user
      user:
          name: "{{ username['uname']['name'] }}"
          password: test
          comment: "{{ username['uname']['desc'] }}"
          state: absent
