---
- name: Ensure that yaya user is present
  hosts: all
  become: true
  vars:
    username: yaya
    uid: 4004

  tasks:
    - name: Create user
      user:
          name: "{{ username }}"
          password: test
          uid: "{{ uid }}"
          state: present

