- name: Testing Jinja Templation
  hosts: all
  become: true

  tasks:
    - name: Deploying message of the day templating
      template:
        src: host.an.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"



